ciudades_aeropuertos = {
    # Ciudades Europeas
    "Madrid": ["MAD"],
    "París": ["CDG", "ORY"],
    "Londres": ["LHR", "LGW", "LCY", "STN", "LTN"],
    "Berlín": ["BER"],
    "Roma": ["FCO", "CIA"],
    "Ámsterdam": ["AMS"],
    "Lisboa": ["LIS"],
    "Bruselas": ["BRU", "CRL"],
    "Viena": ["VIE"],
    "Estocolmo": ["ARN", "BMA"],
    "Moscú": ["SVO", "DME", "VKO"],
    "Atenas": ["ATH"],
    "Copenhague": ["CPH"],
    "Oslo": ["OSL"],
    "Dublín": ["DUB"],
    "Helsinki": ["HEL"],
    "Zúrich": ["ZRH"],
    "Varsovia": ["WAW", "WMI"],
    "Praga": ["PRG"],
    "Budapest": ["BUD"],
    "Múnich": ["MUC"],
    "Barcelona": ["BCN"],
    "Milán": ["MXP", "LIN", "BGY"],
    "Frankfurt": ["FRA"],
    "Hamburgo": ["HAM"],
    "Niza": ["NCE"],

    # Capitales de América
    "Washington D.C.": ["IAD", "DCA"],
    "Brasilia": ["BSB"],
    "Buenos Aires": ["EZE", "AEP"],
    "Ciudad de México": ["MEX"],
    "Bogotá": ["BOG"],
    "Santiago de Chile": ["SCL"],
    "Lima": ["LIM"],
    "Caracas": ["CCS"],
    "Ottawa": ["YOW"],
    "Montevideo": ["MVD"],
    "Asunción": ["ASU"],
    "La Paz": ["LPB"],
    "Quito": ["UIO"],
    "San José": ["SJO"],
    "Panamá": ["PTY"],
    "La Habana": ["HAV"],
    "Santo Domingo": ["SDQ"],
    "San Salvador": ["SAL"],
    "Guatemala City": ["GUA"],
    "Tegucigalpa": ["TGU"],
    "Managua": ["MGA"],
    "Port-au-Prince": ["PAP"],
    "Kingston": ["KIN"],

    # Capitales de Asia
    "Tokio": ["NRT", "HND"],
    "Pekín": ["PEK", "PKX"],
    "Nueva Delhi": ["DEL"],
    "Seúl": ["ICN", "GMP"],
    "Bangkok": ["BKK", "DMK"],
    "Singapur": ["SIN"],
    "Yakarta": ["CGK"],
    "Manila": ["MNL"],
    "Hanoi": ["HAN"],
    "Riad": ["RUH"],
    "Dubái": ["DXB"],
    "Doha": ["DOH"],
    "Teherán": ["IKA", "THR"],
    "Bagdad": ["BGW"],
    "Kuwait City": ["KWI"],
    "Abu Dabi": ["AUH"],
    "Amán": ["AMM"],
    "Kuala Lumpur": ["KUL"],
    "Phnom Penh": ["PNH"],
    "Vientiane": ["VTE"],
    "Katmandú": ["KTM"],
    "Islamabad": ["ISB"],
    "Tiflis": ["TBS"],
    "Bakú": ["GYD"]
}

aerolineas_amadeus = {
    "AA": "American Airlines",
    "AF": "Air France",
    "AM": "Aeroméxico",
    "AR": "Aerolíneas Argentinas",
    "AS": "Alaska Airlines",
    "AT": "Royal Air Maroc",
    "AV": "Avianca",
    "AY": "Finnair",
    "AZ": "Alitalia",
    "BA": "British Airways",
    "BI": "Royal Brunei Airlines",
    "BR": "EVA Air",
    "BT": "Air Baltic",
    "CA": "Air China",
    "CI": "China Airlines",
    "CM": "Copa Airlines",
    "CX": "Cathay Pacific",
    "CZ": "China Southern Airlines",
    "DL": "Delta Air Lines",
    "EI": "Aer Lingus",
    "EK": "Emirates",
    "ET": "Ethiopian Airlines",
    "EY": "Etihad Airways",
    "FJ": "Fiji Airways",
    "GA": "Garuda Indonesia",
    "GF": "Gulf Air",
    "G3": "Gol Linhas Aéreas",
    "HA": "Hawaiian Airlines",
    "HU": "Hainan Airlines",
    "IB": "Iberia",
    "JL": "Japan Airlines",
    "JP": "Adria Airways",
    "JU": "Air Serbia",
    "KE": "Korean Air",
    "KL": "KLM Royal Dutch Airlines",
    "LA": "LATAM Airlines",
    "LO": "LOT Polish Airlines",
    "LH": "Lufthansa",
    "LY": "El Al Israel Airlines",
    "MF": "XiamenAir",
    "MH": "Malaysia Airlines",
    "MK": "Air Mauritius",
    "MS": "EgyptAir",
    "MU": "China Eastern Airlines",
    "NH": "All Nippon Airways (ANA)",
    "NZ": "Air New Zealand",
    "OS": "Austrian Airlines",
    "OU": "Croatia Airlines",
    "OZ": "Asiana Airlines",
    "PG": "Bangkok Airways",
    "PR": "Philippine Airlines",
    "PS": "Ukraine International Airlines",
    "QR": "Qatar Airways",
    "QF": "Qantas Airways",
    "RJ": "Royal Jordanian",
    "RO": "TAROM",
    "RS": "Air Seoul",
    "SK": "SAS Scandinavian Airlines",
    "SN": "Brussels Airlines",
    "SQ": "Singapore Airlines",
    "SU": "Aeroflot",
    "SV": "Saudia",
    "TA": "TACA Airlines",
    "TG": "Thai Airways",
    "TK": "Turkish Airlines",
    "TN": "Air Tahiti Nui",
    "TP": "TAP Air Portugal",
    "UA": "United Airlines",
    "UX": "Air Europa",
    "VA": "Virgin Australia",
    "VN": "Vietnam Airlines",
    "VS": "Virgin Atlantic",
    "VY": "Vueling",
    "WE": "Thai Smile",
    "WN": "Southwest Airlines",
    "WS": "WestJet",
    "WY": "Oman Air",
    "Y4": "Volaris",
    "ZB": "Monarch Airlines",
    "ZL": "Regional Express (REX)",
    "6E": "IndiGo",
    "9W": "Jet Airways",
    "D7": "AirAsia X",
    "DJ": "Virgin Blue Airlines",
    "DY": "Norwegian Air Shuttle",
    "B6": "JetBlue Airways",
    "XY": "Flynas",
    "MH": "Malaysia Airlines",
    "ZL": "Regional Express (REX)",
    "TZ": "Scoot",
    "AK": "AirAsia",
    "VJ": "VietJet Air",
    "HY": "Uzbekistan Airways"
}


